### ISSUE TITLE
Failed to load the language-autohotkey package

### ISSUE THREAD

**Issue by theVKC** [nshakin/language-autohotkey#18]
This issue pops up every time I start Atom, since the 1.1 upgrade. Thanks a bunch!

---

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-autohotkey](https://github.com/nshakin/language-autohotkey) package, v0.1.0

### Stack Trace

Failed to load the language-autohotkey package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\Veronica\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:4:199)
    at C:\Users\Veronica\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:9:5
    at Object.<anonymous> (C:\Users\Veronica\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:52:5)
    at Object.<anonymous> (C:\Users\Veronica\.atom\packages\language-autohotkey\lib\language-autohotkey-view.coffee:54:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Veronica\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
autoclose-html, v0.19.0
language-autohotkey, v0.1.0
language-vbscript, v0.6.1

# Dev
No dev packages
```

**Comment by ROFLLOLSTER** [comment]
+1

**Comment by aush** [comment]
I had the same problem, switched to atom-beta, and it was gone, but with a new update I have this problem again.

Atom 1.2.0-beta2

**Comment by neilthomson** [comment]
+1

**Comment by marsiau** [comment]
+1

**Comment by highend** [comment]
Same problem, can this be fixed, please?

**Comment by mr-moon** [comment]
+1

**Comment by theVKC** [comment]
@nshakin: are you still working on this project? I find it quite useful, and if you are no longer involved I might be interested in forking this project and continuing the work.

**Comment by hosicame** [comment]
+1

**Comment by GDur** [comment]
+1

**Comment by Paulix** [comment]
+1

**Comment by vanillaSprinkles** [comment]
+1

I was able to fix this by editing: package.json
- "main": "./lib/language-autohotkey"
+ "main": "./language-autohotkey"

**Comment by Paulix** [comment]
@theVKC vanillaSprinkles 
Thank You! :+1: :+1: :+1:

**Comment by Paulix** [comment]
Error Message is gone, functionality also ;-)

**Comment by theVKC** [comment]
That did seem to solve the problem. Thanks @vanillaSprinkles!

I'm hoping this package is still being maintained. I might have a crack at creating my own someday if this isn't. As the source file is still glitchy, I'm not going to close my issue.

**Comment by vanillaSprinkles** [comment]
I was thinking of doing similar; going through everybody's forks and merging in them into one branch. Might work on it more tonight if people don't beat me to it.

**Comment by theVKC** [comment]
Go for it, @vanillaSprinkles, and thank you!

**Comment by nshakin** [comment]
Hey Veronica,

I am glad you find this project useful. I no longer have time for this and
would appreciate if you forked it and continued the work. Please keep me
informed to any progress!

Thanks,


*-------------------------*

*Nicholas Shakin*
nshakin@gmail.com
(630)765-0852

On Tue, Dec 8, 2015 at 2:56 PM, Veronica Kahl Cary <notifications@github.com

**Comment by vanillaSprinkles** [comment]
@theVKC:
just returned to this and looking at the forks, the user cescue has gone ahead and forked this and a handful of other useful pieces.

@nshakin: 
thanks for letting us know, appreciate the jumpstart

**Comment by zacps** [comment]
@nshakin Could you add a depreciation notice to the readme with a link to cescue's fork?

**Comment by ipstone** [comment]
hi buddies, it seems that vanillaSprinkles's edit has fixed it, shouldn't this be updated in the main branch and this ticket gets closed? it was opened for two months.

+1

I was able to fix this by editing: package.json
"main": "./language-autohotkey"

**Comment by zacps** [comment]
@ipstone The author is nowhere to be found and isn't accepting pull requests/closing issues cescue has a fork of this project that may or may not be active.

**Comment by vanillaSprinkles** [comment]
I have been using and adding to cescue's fork of this project (https://github.com/cescue/language-autohotkey). We will soon be trying to integrate it into atom.io's packages list properly - issues are open on that fork as well.

**Comment by theVKC** [comment]
I'd be happy to close this issue, but I'm thinking a depreciation notice + link should be in order. @nshakin: I know you aren't active with this anymore, but it would be very helpful.
@vanillaSprinkles: once the integration into the package list goes through, can you comment here? That might be a great point to close the issue.

**Comment by nshakin** [comment]
Sorry everyone for dropping the project.
@theVKC: I will update the readme with a deprecation notice.  What should I link to as the current best fork of the project?

**Comment by joedf** [comment]
@nshakin I presume [this one](https://github.com/cescue/language-autohotkey)?

**Comment by nshakin** [comment]
Thanks @joedf.  I will update the readme with cescue's fork.

**Comment by vanillaSprinkles** [comment]
@theVKC yes I will post here once the integration to atom.io is working fully (I know it is on cescue's to-do list). it's been a busy last few weeks for me so I have not worked on it much

@nshakin: dropped projects happen; life happens. a big thanks for updating the readme and checking in when you are able to

**Comment by Muffinoota** [comment]
Hopefully I'm not too late. I have a syntax highlighter of sorts for notepad++.
Given how AHK is, pretty much everything is a keyword, with regex really only being needed for the two types of comments, variables, things in quotes, and numbers.
Here's a screenshot of the highlighter.
Should I just fork and rewrite using what I have? Or have you folks already finished?
![93f3256bc54a2fd6ea1dde83610a2f29](https://cloud.githubusercontent.com/assets/16392448/12404314/fbda11b4-bdff-11e5-8c31-b3540d4ac6ad.png)

**Comment by jonatastrife** [comment]
+1

**Comment by THernandez03** [comment]
+1

**Comment by Gubith** [comment]
+1

**Comment by ghost** [comment]
Closing this issue. For folks using it, there's a new fork of the project which is working: https://github.com/cescue/language-autohotkey.
